name: Firebase Deploy

on:
  push:
    branches:
      - develop
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: |
          cd functions
          npm install

      # w9jds/firebase-actionを利用してfirebaseにデプロイ
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{secrets.PROJECT_ID}}
